language: python

python:
    - "2.7"

install:
    - python setup.py install
    - mkdir ~/.taca && cp tests/data/taca_test_cfg.yaml ~/.taca/taca.yaml

script:
    - cd tests && nosetests -v -s

notifications:
    email: false
